meson: Fix build with meson 1.2.1
Use a list in link_with instead of a single value.  Fixes the following:

```
   File "/usr/lib/python3.11/site-packages/mesonbuild/modules/rust.py", line 163, in test
       new_target_kwargs['link_with'] = new_target_kwargs.get('link_with', []) + kwargs['link_with']
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
   TypeError: unsupported operand type(s) for +: 'StaticLibrary' and 'list'

   src/meson.build:6:9: ERROR: Unhandled python exception
```